function mSendMsg(obj,robot,currentTime)

if nargin < 3
    currentTime = 0;
end

obj.pMSG.setTo = [];

Type = class(robot);

% Construct message
switch Type(1)
    % Pioneer 3DX
    case 'P' 
        % Padrão pioneer (duas variáveis de controle)
        obj.pMSG.setTo = sprintf(['[%0.0f#%0.0f#' ...
            'Xd,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
            'X,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
            'Ud,%f,%f,'...
            'U,%f,%f,'...
            't,%f,]'],...
            Type(1),...
            robot.pID,...
            robot.pPos.Xd,...
            robot.pPos.X,...
            robot.pSC.Ud(1:2),...
            robot.pSC.U(1:2),...
            currentTime);


% Padrão drone (4 variaveis de controle)
%  obj.pMSG.setTo = sprintf(['[%0.0f#%0.0f#' ...
%             'Xd,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
%             'X,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
%             'Ud,%f,%f,%f,%f,'...
%             'U,%f,%f,%f,%f,]'],...
%             Type(1),...
%             robot.pID,...
%             robot.pPos.Xd,...
%             robot.pPos.X,...
%             robot.pSC.Ud,...
%             robot.pSC.U);

    % ArDrone2    
    case 'A' 
        obj.pMSG.setTo = sprintf(['[%0.0f#%0.0f#' ...
            'Xd,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
            'X,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,' ...
            'Ud,%f,%f,%f,%f,'...
            'U,%f,%f,%f,%f,]'],...
            Type(1),...
            robot.pID,...
            robot.pPos.Xd,...
            robot.pPos.X,...
            robot.pSC.Ud,...
            robot.pSC.U);
        
    otherwise
        disp('Robot type not found! It have to be ArDrone or Pioneer3DX only, man!')
end

fprintf(obj.pUDP,obj.pMSG.setTo); 
% size(obj.pMSG.setTo)



