close all; clear all; clc;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -%
% PLOT DOS RESULTADOS DO EXPERIMENTO
% Refinando os dados
% DADOS = evalin('base','DADOS');
load '202001302257_AgoraFoi.mat'
%%
for ii = 1:size(DADOS,2)
    ETAPAS{ii} = DADOS{ii}(:,end-1:end);
    PARTE = 1;
    PARTE_REAL = 1;
    TEMPOS = [128];
%     TEMPOS = [30 75 128];
    while ETAPAS{ii}(1,2) > TEMPOS(PARTE)
        PARTE = PARTE + 1;
    end
    TEMPOS_REAIS = [30 37.5 45 60 75 90 97.5 128];
    while ETAPAS{ii}(1,2) > TEMPOS_REAIS(PARTE_REAL)
        PARTE_REAL = PARTE_REAL + 1;
    end
    DRONES = [1 1 0 0; 1 1 0 0; 0 1 0 0; 0 1 0 0; 0 1 0 0; 1 1 0 0; 1 1 0 0; 1 1 0 0];
    FORMACAO = [1 1 0; 0 1 0; 0 1 0; 0 1 0; 0 1 0; 0 1 1; 0 1 1; 0 1 1];
    PIONEER = FORMACAO;
    F_ROBO{1} = [1 1 3; 1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0];
    F_ROBO{2} = [2 2 4; 2 2 1; 2 2 1; 2 2 1; 2 2 1; 2 1 4; 2 1 4; 2 1 4];
    F_ROBO{3} = [3 0 0; 3 0 0; 3 0 0; 3 0 0; 3 0 0; 3 2 3; 3 2 3; 3 2 3];
    ROBOS = [DRONES FORMACAO PIONEER F_ROBO{ii}];
    for jj = 1:size(ETAPAS{ii},1)
        if ETAPAS{ii}(jj,2) > TEMPOS(PARTE)
            PARTE = PARTE + 1;
        end
        if ETAPAS{ii}(jj,2) > TEMPOS_REAIS(PARTE_REAL)
            PARTE_REAL = PARTE_REAL + 1;
        end
        ETAPAS{ii}(jj,1:(1+size(ROBOS,2)+2)) = [PARTE ROBOS(PARTE_REAL,:) ETAPAS{ii}(jj,1:2)];
    end
    PARTE = 1;
    FINAL_PARTE{ii} = find(ETAPAS{ii}(:,1)==PARTE);
    if size(FINAL_PARTE{ii},1) ~= 0
        FINAL_PARTE{ii}(1) = FINAL_PARTE{ii}(1,1);
        FINAL_PARTE{ii}(2) = FINAL_PARTE{ii}(end,1);
        FINAL_PARTE{ii}(3:end) = [];
    end
end
%%
% c = 0;
% for ii = 1:size(FINAL_PARTE,2)
%     if size(FINAL_PARTE{ii+c},1) == 0
%         FINAL_PARTE(ii+c) = [];
%         c = c - 1;
%     end
% end
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -%
% PLOT DOS RESULTADOS DO EXPERIMENTO

%           ETAPAS
%
%           1               2--5            6--8            9--11
%           PARTE           DRONES          FORMACAO        PIONEER
%           
%           12--14          15              16
%           TF{1}.pPar.R    toc(T)          toc(T_ALFA)

F = 1;

%           DADOS
%
%           1 -- 12         13 -- 24        25 -- 26        
%           P.pPos.Xd'      P.pPos.X'       P.pSC.Ud'    
%
%           27 -- 38        39 -- 50        51 -- 62        63 -- 66
%           A{1}.pPos.Xd'   A{1}.pPos.X'    A{1}.pPos.Xr'   A{1}.pSC.U'
%
%           67 -- 78        79 -- 90        91 -- 102       103 -- 106
%           A{2}.pPos.Xd'   A{2}.pPos.X'    A{2}.pPos.Xr'   A{2}.pSC.U'
% 
%           107 -- 115      116 -- 124      125 -- 133      134 -- 142
%           TF.pPos.Qd'     TF.pPos.Q'      TF.pPos.dQd'    TF.pPos.dQr'
% 
%           143 -- 151      152 -- 160      161 -- 169
%           TF.pPos.Xd'     TF.pPos.X'      TF.pPos.dXr'
% 
%           170             171'
%           toc(T)          toc(T_ALFA)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                            PIONEER ATIVOS                               %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AX = {[0 TEMPOS(PARTE) 0.5  1.1]  [0 TEMPOS(PARTE) -0.3 0.3]...
    [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
    [0 TEMPOS(PARTE) -0.1 0.1]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1.1 -0.5] [0 TEMPOS(PARTE) -0.3 0.3]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
      [0 TEMPOS(PARTE) -0.1  0.1]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1.1 -0.5] [0 TEMPOS(PARTE) -0.3 0.3]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
      [0 TEMPOS(PARTE) -0.1  0.1]  [0 TEMPOS(PARTE) -0.1 0.1]};
    
% for ii = 1:size(FINAL_PARTE,2)
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % PIONEER
    if ETAPAS{ii}(FINAL_PARTE{ii}(1),8 + ETAPAS{ii}(FINAL_PARTE{ii}(1),5+ii)) == 1
        fig = figure(F);
        F = F + 1;
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        subplot(311)
        hold on
        grid on
        yyaxis left
        axis(AX{ii,1})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+1),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),1),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,2})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),1)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+1),...
             ':r','LineWidth',1.6);
        legend(['UGV ' num2str(ii) ' position'],['UGV ' num2str(ii) ' desired trajectory'],['UGV ' num2str(ii) ' Error'],'interpreter','latex','orientation','horizontal','location','northoutside');
        subplot(312)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,3})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+2),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),2),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,4})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),2)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+2),...
             ':r','LineWidth',1.6);
        subplot(313)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,5})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+3),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),3),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,6})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),3)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+3),...
             ':r','LineWidth',1.6);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                            ARDRONES ATIVOS                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AX = {[0 TEMPOS(PARTE) 0.6  1]  [0 TEMPOS(PARTE) -0.2 0.2]...
    [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.5 0.5]...
    [0 TEMPOS(PARTE) 1.4 1.6]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1 -0.6] [0 TEMPOS(PARTE) -0.2 0.2]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.5 0.5]...
      [0 TEMPOS(PARTE) 1.4  1.6]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1 -0.6] [0 TEMPOS(PARTE) -0.2 0.2]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.5 0.5]...
      [0 TEMPOS(PARTE) 1.4  1.6]  [0 TEMPOS(PARTE) -0.1 0.1]};
    
% for ii = 1:size(FINAL_PARTE,2)
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % ARDRONE
    if ETAPAS{ii}(FINAL_PARTE{ii}(1),1 + ETAPAS{ii}(FINAL_PARTE{ii}(1),13)) == 1
        fig = figure(F);
        F = F + 1;
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        subplot(311)
        hold on
        grid on
        yyaxis left
        axis(AX{ii,1})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+1),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+1),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,2})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+1)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+1),...
             ':r','LineWidth',1.6);
        legend(['UAV ' num2str(ii) ' position'],['UAV ' num2str(ii) ' desired trajectory'],['UAV ' num2str(ii) ' Error'],'interpreter','latex','orientation','horizontal','location','northoutside');
        subplot(312)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,3})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+2),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+2),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,4})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+2)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+2),...
             ':r','LineWidth',1.6);
        subplot(313)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,5})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+3),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+3),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,6})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),142+3+3)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+3),...
             ':r','LineWidth',1.6);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                          POSI플O DA FORMA플O                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AX = {[0 TEMPOS(PARTE) 0.5  1.1]  [0 TEMPOS(PARTE) -0.3 0.3]...
    [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
    [0 TEMPOS(PARTE) -0.1 0.1]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1.1 -0.5] [0 TEMPOS(PARTE) -0.3 0.3]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
      [0 TEMPOS(PARTE) -0.1  0.1]  [0 TEMPOS(PARTE) -0.1 0.1];
      [0 TEMPOS(PARTE) -1.1 -0.5] [0 TEMPOS(PARTE) -0.3 0.3]...
      [0 TEMPOS(PARTE) -2  2]  [0 TEMPOS(PARTE) -0.6 0.6]...
      [0 TEMPOS(PARTE) -0.1  0.1]  [0 TEMPOS(PARTE) -0.1 0.1]};
    
% for ii = 1:size(FINAL_PARTE,2)
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % FORMATION POSITION
    if ETAPAS{ii}(FINAL_PARTE{ii}(1),1 + ETAPAS{ii}(FINAL_PARTE{ii}(1),5+ii)) == 1
        fig = figure(F);
        F = F + 1;
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        subplot(311)
        hold on
        grid on
        yyaxis left
        axis(AX{ii,1})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+1),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+1),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,2})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+1)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+1),...
             ':r','LineWidth',1.6);
        legend(['Formation ' num2str(ii) ' position'],['Formation ' num2str(ii) ' desired trajectory'],['Formation ' num2str(ii) ' Error'],'interpreter','latex','orientation','horizontal','location','northoutside');
        subplot(312)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,3})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+2),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+2),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,4})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+2)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+2),...
             ':r','LineWidth',1.6);
        subplot(313)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,5})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,6})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3),...
             ':r','LineWidth',1.6);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                        ORIENTA플O DA FORMA플O                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AX = {[0 TEMPOS(PARTE) -4  4]  [0 TEMPOS(PARTE) -4 4]...
      [0 TEMPOS(PARTE) -4  4]  [0 TEMPOS(PARTE) -4 4]...
      [0 TEMPOS(PARTE) 82 98]  [0 TEMPOS(PARTE) -8 8];
      [0 TEMPOS(PARTE) -40  40]  [0 TEMPOS(PARTE) -10 10]...
      [0 TEMPOS(PARTE) -4  4]  [0 TEMPOS(PARTE) -4 4]...
      [0 TEMPOS(PARTE) -180 360]  [0 TEMPOS(PARTE) -8 8];
      [0 TEMPOS(PARTE) -4  4]  [0 TEMPOS(PARTE) -4 4]...
      [0 TEMPOS(PARTE) -4  4]  [0 TEMPOS(PARTE) -4 4]...
      [0 TEMPOS(PARTE) 82 98]  [0 TEMPOS(PARTE) -8 8]};
    
% for ii = 1:size(FINAL_PARTE,2)
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % FORMATION ORIENTATION
    if ETAPAS{ii}(FINAL_PARTE{ii}(1),1 + ETAPAS{ii}(FINAL_PARTE{ii}(1),5+ii)) == 1
        fig = figure(F);
        F = F + 1;
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        subplot(311)
        hold on
        grid on
        yyaxis left
        axis(AX{ii,1})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+1)*180/pi,...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+1)*180/pi,...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,2})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+1)*180/pi-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+1)*180/pi,...
             ':r','LineWidth',1.6);
        legend(['Formation ' num2str(ii) ' orientation'],['Formation ' num2str(ii) ' desired trajectory'],['Formation ' num2str(ii) ' Error'],'interpreter','latex','orientation','horizontal','location','northoutside');
        subplot(312)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,3})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+2)*180/pi,...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+2)*180/pi,...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,4})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+2)*180/pi-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+2)*180/pi,...
             ':r','LineWidth',1.6);
        subplot(313)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,5})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+3)*180/pi,...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+3)*180/pi,...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,6})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+3+3)*180/pi-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+3+3)*180/pi,...
             ':r','LineWidth',1.6);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                          POSTURA DA FORMA플O                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AX = {[0 TEMPOS(PARTE) 1.4  1.6]  [0 TEMPOS(PARTE) -0.1 0.1]...
      [0 TEMPOS(PARTE) 1.4  2.3]  [0 TEMPOS(PARTE) -0.45 0.45]...
      [0 TEMPOS(PARTE) 26 46]  [0 TEMPOS(PARTE) -10 10];
      [0 TEMPOS(PARTE) -0.3  2.3]  [0 TEMPOS(PARTE) -0.8 0.8]...
      [0 TEMPOS(PARTE) -0.3  2.3]  [0 TEMPOS(PARTE) -0.8 0.8]...
      [0 TEMPOS(PARTE) 22 50]  [0 TEMPOS(PARTE) -10 10];
      [0 TEMPOS(PARTE) 1.4  1.6]  [0 TEMPOS(PARTE) -0.1 0.1]...
      [0 TEMPOS(PARTE) 1.4  2.3]  [0 TEMPOS(PARTE) -0.45 0.45]...
      [0 TEMPOS(PARTE) 26 46]  [0 TEMPOS(PARTE) -10 10]};
    
% for ii = 1:size(FINAL_PARTE,2)
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % FORMATION POSE
    if ETAPAS{ii}(FINAL_PARTE{ii}(1),1 + ETAPAS{ii}(FINAL_PARTE{ii}(1),5+ii)) == 1
        fig = figure(F);
        F = F + 1;
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        subplot(311)
        hold on
        grid on
        yyaxis left
        axis(AX{ii,1})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+1),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+1),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,2})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+1)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+1),...
             ':r','LineWidth',1.6);
        legend(['Formation ' num2str(ii) ' pose'],['Formation ' num2str(ii) ' desired trajectory'],['Formation ' num2str(ii) ' Error'],'interpreter','latex','orientation','horizontal','location','northoutside');
        subplot(312)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,3})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+2),...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+2),...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,4})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+2)-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+2),...
             ':r','LineWidth',1.6);
        subplot(313)
        left_color = [0 0 0];
        right_color = [0 0 0];
        set(fig,'defaultAxesColorOrder',[left_color; right_color]);
        hold on
        grid on
        yyaxis left
        axis(AX{ii,5})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+3)*180/pi,...
             '-b','LineWidth',1.6);
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+3)*180/pi,...
             '--k','LineWidth',1.6);
        yyaxis right
        axis(AX{ii,6})
        plot(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),end)-...
             DADOS{ii}(FINAL_PARTE{ii}(1),end),...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),106+6+3)*180/pi-...
             DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),115+6+3)*180/pi,...
             ':r','LineWidth',1.6);
    end
end

COLOR = {'r' 'g' 'b'};

fig = figure(F);
F = F + 1;
% for ii = 1:size(FINAL_PARTE,2)
%%
for ii = find(ETAPAS{2}(FINAL_PARTE{2}(1),6:8) == 1)
    % SIMULA플O
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),12+3),...
          ['--' COLOR{ii}],'LineWidth',1.6);
    hold on
    grid on
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),38+3),...
          ['-' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1),12+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1),12+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1),12+3),...
          ['s' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1),38+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1),38+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1),38+3),...
          ['x' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(2),12+1),...
          DADOS{ii}(FINAL_PARTE{ii}(2),12+2),...
          DADOS{ii}(FINAL_PARTE{ii}(2),12+3),...
          ['o' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(2),38+1),...
          DADOS{ii}(FINAL_PARTE{ii}(2),38+2),...
          DADOS{ii}(FINAL_PARTE{ii}(2),38+3),...
          ['^' COLOR{ii}],'LineWidth',2,'MarkerSize',10);
    if ETAPAS{ii}(FINAL_PARTE{ii},1+ETAPAS{ii}(FINAL_PARTE{ii},14)) == 1
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),78+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),78+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1):FINAL_PARTE{ii}(2),78+3),...
          ['-' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(1),78+1),...
          DADOS{ii}(FINAL_PARTE{ii}(1),78+2),...
          DADOS{ii}(FINAL_PARTE{ii}(1),78+3),...
          ['x' COLOR{ii}],'LineWidth',2,'MarkerSize',15);
    plot3(DADOS{ii}(FINAL_PARTE{ii}(2),78+1),...
          DADOS{ii}(FINAL_PARTE{ii}(2),78+2),...
          DADOS{ii}(FINAL_PARTE{ii}(2),78+3),...
          ['^' COLOR{ii}],'LineWidth',2,'MarkerSize',10);
    end
    axis equal
end
%%
lgd = legend('UGV 1 trace','UAV 1 trace','UGV 1 initial position','UAV 1 final position','UGV 1 initial position','UAV 1 final position',...
       'UGV 2 trace','UAV 2 trace','UGV 2 initial position','UAV 2 final position','UGV 2 initial position','UAV 2 final position',...
       'interpreter','latex','location','northoutside');
   
lgd.NumColumns = 4;
   
   
   
   